Notebook 2 and 5 Update - Haolin
bwsi-hadr-2024/bwsi-modules-2024 pull request #3
Opened 2024-07-06 06:08 UTC by HumblePasty

- Bug fixes on code, now code can run without error in the remote environment
- Adjustment on markdown contents based on standup meeting discussions

Notes:
- The old notebook is now replaced
- Each module has two versions of notebook
- The xxx_w_solution.ipynb version contains sample solutions for the exercises

Standing issues:
- Update for module 08 (deep learning) is not available yet
- GDAL command line may not execute properly in the remote environment (see the last code block in 5a)

2024-07-06 18:23 UTC, sscheele requested changes

2024-07-06 18:23 UTC, sscheele commented on 07-3D_Reconstruction_and_SfM/07-Structure-from-motion.ipynb
Did you mean to commit this? It looks like all of your cells failed

2024-07-06 18:23 UTC, sscheele commented on 08-Intro_to_deep_learning/08b-Training-Neural-Network.ipynb
It seems like many cells in this notebook also failed

2024-07-06 21:54 UTC, HumblePasty commented on 02-visualization-and-shapes/02_Visualization_and_Shapes.ipynb
Sure I removed the solution from the file and now it is gone!

2024-07-06 22:00 UTC, HumblePasty commented on 05-Rasters-and-satellite-imagery/05a_Intro_to_rasters.ipynb
Thanks for the reminder! I added the magic lines for `mamba` installation for gdal. Hopefully it will help.

2024-07-06 22:08 UTC, HumblePasty commented on 07-3D_Reconstruction_and_SfM/07-Structure-from-motion.ipynb
No, Jake and I were then trying to have the opensfm environment problem sorted out days earlier so that's why there are a lot of errors in the file. Now that we are using the remote environment I think we can simply add magic commands before we want to use opensfm cli.

I think Jake is working on updating this one so for now, I deleted my version and replaced it with the original notebook in my personal branch to avoid conflict.

One thing I have noticed about this notebook though is that our image data is loaded using relative paths. So I am not sure whether it would cause trouble in remote environment. Maybe having a clone of the whole repo in the remote environment would help.

2024-07-06 22:11 UTC, HumblePasty commented on 08-Intro_to_deep_learning/08b-Training-Neural-Network.ipynb
I am still working on updating this notebook currently.

For now, I replaced the file with the original one (with Jeff's changes).

I'll push changes and make another pull request for this one once I have all the issues solved.

2024-07-06 22:23 UTC, HumblePasty commented
Reviewed comments and updated the branch

2024-07-07 03:18 UTC, sscheele approved these changes

2024-07-07 03:18 UTC, merged